meta_product_name: "Anthony Shaw"
meta_title: "Anthony Shaw | Copywriter | Creative Professional"
meta_description: "Looking for a UK-based copywriter?"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@anthonyjshaw"   # required for Twitter Cards
