meta_product_name: "Anthony Shaw"
meta_title: "Anthony Shaw"
meta_description: "Full stack web developer "
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
