meta_product_name: "Anthony Shaw"
meta_title: "Anthony Shaw | Copywriter"
meta_description: "Experienced creative copywriter"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@anthonyjshaw"   # required for Twitter Cards